<!DOCTYPE html>
<html>
<head>
<title><?=$meta->title?></title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="baseUrl" content="<?=HOST?>" />
<meta name="themeUrl" content="<?=$this->options->themeUrl?>" />
<?php $this->writeMeta(); ?>
<?php Plugin::triggerEvent('theme.head'); ?>
<link rel="shortcut icon" type="image/x-icon" href="<?=$this->options->themeUrl?>/images/favicon.ico" />
<!-- <link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/css/main.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/css/account.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/css/responsive.css" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/css/flat-ui-pro.min.css" /> -->
<link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/css/videojs-sublime-skin.min.css" />
<!-- Initialise FLat UI -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/assets/css/vendor/bootstrap.min.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/assets/css/flat-ui-pro.css" rel="stylesheet" />

<!-- Add Lato Font -->
<link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
 <!-- Annotator -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
        <script src="http://assets.annotateit.org/annotator/v1.2.5/annotator-full.min.js"></script>
        <link rel="stylesheet" href="http://assets.annotateit.org/annotator/v1.2.5/annotator.min.css">

<!--RangeSlider Pluging-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/rangeslider.js/2.1.1/rangeslider.min.js"></script>
	<link href="https://cdnjs.cloudflare.com/ajax/libs/rangeslider.js/2.1.1/rangeslider.min.css">

<!--Annotations Pluging-->
        <link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/css/annotator.min.css" />

<?php $this->writeCSS(); ?>

</head>
<body class="<?=$this->cssHooks()?>">
<?php Plugin::triggerEvent('theme.body'); ?>

<?php $this->block('header.phtml'); ?>
                <!-- Login Modal -->
                <div class="modal fade in" id="modal-container-855933" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                    ×
                                </button>
                                <h4 class="modal-title" id="myModalLabel">Login</h4>
                            </div>
                            <div class="modal-body">
                                <form class="navbar-form navbar-left" role="search">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Username">
                                    </div>
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Password">
                                    </div>
                                    <!-- <button type="submit" class="btn btn-default">
                                        Login
                                    </button> -->
                                </form>
                            </div>
                            <div class="modal-footer">
                                <!-- <button type="button" class="btn btn-default" data-dismiss="modal">
                                    Close
                                </button> -->
                                <button type="button" class="btn btn-primary">
                                    Login
                                </button>
                                <a href="<?=HOST?>/register/" title="<?=Language::GetText('register')?>"><?=Language::GetText('register')?></a>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Login Modal -->
<div class="container">
    <div class="row">
                
        <!-- BEGIN SIDEBAR -->
        <div class="hidden-xs hidden-sm col-md-3">
            <div class="account-menu">
                <p class="h4"><?=Language::GetText('manage_media')?></p>
                <ul>
                    <?php if ($config->enableUserUploads): ?>
                        <li><a href="<?php echo HOST; ?>/account/upload/" title="<?=Language::GetText('upload_video')?>"><?=Language::GetText('upload_video')?></a></li>
                        <li><a href="<?php echo HOST; ?>/account/videos/" title="<?=Language::GetText('my_videos')?>"><?=Language::GetText('my_videos')?></a></li>
                    <?php endif; ?>
                    <li><a href="<?php echo HOST; ?>/account/playlists/" title="<?=Language::GetText('my_playlists')?>"><?=Language::GetText('my_playlists')?></a></li>
                </ul>

                <p class="h4"><?=Language::GetText('account_settings')?></p>
                <ul>
                    <li><a href="<?php echo HOST; ?>/account/profile/" title="<?=Language::GetText('update_profile')?>"><?=Language::GetText('update_profile')?></a></li>
                    <li><a href="<?php echo HOST; ?>/account/privacy-settings/" title="<?=Language::GetText('privacy_settings')?>"><?=Language::GetText('privacy_settings')?></a></li>
                    <li><a href="<?php echo HOST; ?>/account/change-password/" title="<?=Language::GetText('change_password')?>"><?=Language::GetText('change_password')?></a></li>
                </ul>

                <p class="h4"><?=Language::GetText('community')?></p>
                <ul>
                    <li><a href="<?php echo HOST; ?>/account/subscriptions/" title="<?=Language::GetText('my_subscriptions')?>"><?=Language::GetText('my_subscriptions')?></a></li>
                    <li><a href="<?php echo HOST; ?>/account/subscribers/" title="<?=Language::GetText('my_subscribers')?>"><?=Language::GetText('my_subscribers')?></a></li>
                    <li><a href="<?php echo HOST; ?>/account/message/inbox/" title="<?=Language::GetText('inbox')?>"><?=Language::GetText('inbox')?></a></li>
                    <li><a href="<?php echo HOST; ?>/account/message/send/" title="<?=Language::GetText('send_message')?>"><?=Language::GetText('send_message')?></a></li>
                </ul>
            </div>
            <?php $this->writeSidebarBlocks(); ?>
        </div>
        <!-- END SIDEBAR -->

        <!-- BEGIN Mobile/Table Account Menu -->
        <div class="hidden visible-xs-block visible-sm-block col-xs-12 mobile-account-menu">
        <div class="dropdown">
            <button class="btn btn-default btn-block dropdown-toggle" type="button" data-toggle="dropdown">
                <?=Language::GetText('account_menu_header')?>
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu col-xs-12">
                <li class="dropdown-header"><?=Language::GetText('manage_media')?></li>
                <?php if ($config->enableUserUploads): ?>
                    <li><a href="<?php echo HOST; ?>/account/upload/" title="<?=Language::GetText('upload_video')?>"><?=Language::GetText('upload_video')?></a></li>
                    <li><a href="<?php echo HOST; ?>/account/videos/" title="<?=Language::GetText('my_videos')?>"><?=Language::GetText('my_videos')?></a></li>
                <?php endif; ?>
                <li><a href="<?php echo HOST; ?>/account/playlists/" title="<?=Language::GetText('my_playlists')?>"><?=Language::GetText('my_playlists')?></a></li>


                <li class="dropdown-header"><?=Language::GetText('account_settings')?></li>
                <li><a href="<?php echo HOST; ?>/account/profile/" title="<?=Language::GetText('update_profile')?>"><?=Language::GetText('update_profile')?></a></li>
                <li><a href="<?php echo HOST; ?>/account/privacy-settings/" title="<?=Language::GetText('privacy_settings')?>"><?=Language::GetText('privacy_settings')?></a></li>
                <li><a href="<?php echo HOST; ?>/account/change-password/" title="<?=Language::GetText('change_password')?>"><?=Language::GetText('change_password')?></a></li>
           

                <li class="dropdown-header"><?=Language::GetText('community')?></li>
                <li><a href="<?php echo HOST; ?>/account/subscriptions/" title="<?=Language::GetText('my_subscriptions')?>"><?=Language::GetText('my_subscriptions')?></a></li>
                <li><a href="<?php echo HOST; ?>/account/subscribers/" title="<?=Language::GetText('my_subscribers')?>"><?=Language::GetText('my_subscribers')?></a></li>
                <li><a href="<?php echo HOST; ?>/account/message/inbox/" title="<?=Language::GetText('inbox')?>"><?=Language::GetText('inbox')?></a></li>
                <li><a href="<?php echo HOST; ?>/account/message/send/" title="<?=Language::GetText('send_message')?>"><?=Language::GetText('send_message')?></a></li>
            </ul></div>
        </div>
        <!-- END Mobile/Table Account Menu -->

        <!-- BEGIN MAIN CONTENT -->
        <main class="col-xs-12 col-md-9">
            <?=$this->body()?>
        </main>
        <!-- END MAIN CONTENT -->

    </div>
</div>

<?php $this->block('footer.phtml'); ?>   

<script type="text/javascript" src="<?=$this->options->themeUrl?>/js/jquery.min.js"></script>
<script type="text/javascript" src="<?=$this->options->themeUrl?>/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="<?=$this->options->themeUrl?>/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?=$this->options->themeUrl?>/js/general.js"></script>
<script type="text/javascript" src="<?=$this->options->themeUrl?>/js/annotator.min.js"></script>
<!-- Start Facebook SDK -->
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1116913425020741',
      xfbml      : true,
      version    : 'v2.5'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
<!-- End Facebook SDK -->

<!-- Carousel Preferences Start-->
<script> 
var $ = jQuery.noConflict(); $(document).ready(function()  { $('#carousel-584841').carousel({ interval: 3000, cycle: true }); });
</script>
<!-- Carousel Preferences End-->

<?php $this->writeJs(); ?>
    <!-- jQuery (necessary for Flat UI's JavaScript plugins) -->
    <script src="assets/js/vendor/jquery.min.js"></script>
    <script src="assets/js/vendor/video.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="assets/js/flat-ui-pro.js"></script>

</body>
</html>
