<?php $this->setLayout('full'); ?>

<?php if ($logout): ?>
    <div class="alert alert-success"><?=Language::getText('success_logout')?></div>
<?php endif; ?>
<div class="container-fluid">
        <div class="row">
            <div class="col-md-12" style="background-image: url(assets/img/minions.jpg); height: 100vh;">
                <nav class="navbar navbar-inverse" role="navigation" style="margin-top: 10px;">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
                        </button> <a class="navbar-brand" href="#">IndiePlat</a>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="#">Films</a>
                            </li>
                            <li>
                                <a id="modal-855933" href="#modal-container-855933" role="button" class="btn" data-toggle="modal">Artists</a>
                            </li>
                            <li>
                                <a id="modal-855933" href="#modal-container-855933" role="button" class="btn" data-toggle="modal">Upload</a>
                            </li>
                            <!-- <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong class="caret"></strong></a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="#">Action</a>
                                    </li>
                                    <li>
                                        <a href="#">Another action</a>
                                    </li>
                                    <li>
                                        <a href="#">Something else here</a>
                                    </li>
                                    <li class="divider">
                                    </li>
                                    <li>
                                        <a href="#">Separated link</a>
                                    </li>
                                    <li class="divider">
                                    </li>
                                    <li>
                                        <a href="#">One more separated link</a>
                                    </li>
                                </ul>
                            </li> -->
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a id="modal-855933" href="#modal-container-855933" role="button" class="btn" data-toggle="modal">Login</a>
                            </li>
                            <!-- <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong class="caret"></strong></a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="#">Action</a>
                                    </li>
                                    <li>
                                        <a href="#">Another action</a>
                                    </li>
                                    <li>
                                        <a href="#">Something else here</a>
                                    </li>
                                    <li class="divider">
                                    </li>
                                    <li>
                                        <a href="#">Separated link</a>
                                    </li>
                                </ul>
                            </li> -->
                            <!-- <form class="navbar-form navbar-left" role="search">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Search">
                                </div>
                                <button type="submit" class="btn btn-default">
                                    Search
                                </button>
                            </form> -->
                            <form class="navbar-form navbar-left" role="search">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Search" id="search-query-3">
                                        <span class="input-group-btn">
                                            <button type="submit" class="btn"><span class="fui-search"></span></button>
                                        </span>
                                    </div>
                                </div>
                            </form>
                        </ul>
                    </div>
                </nav>
                <!-- Login Modal -->
                <div class="modal fade in" id="modal-container-855933" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                    ×
                                </button>
                                <h4 class="modal-title" id="myModalLabel">Login</h4>
                            </div>
                            <div class="modal-body">
                                <form class="navbar-form navbar-left" role="search">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Username">
                                    </div>
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Password">
                                    </div>
                                    <!-- <button type="submit" class="btn btn-default">
                                        Login
                                    </button> -->
                                </form>
                            </div>
                            <div class="modal-footer">
                                <!-- <button type="button" class="btn btn-default" data-dismiss="modal">
                                    Close
                                </button> -->
                                <button type="button" class="btn btn-primary">
                                    Login
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Login Modal -->
            </div>
        </div>
