<?php $this->setLayout('full'); ?>

<?php if ($logout): ?>
    <div class="alert alert-success"><?=Language::getText('success_logout')?></div>
<?php endif; ?>

<!-- Start Carousel -->
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="carousel slide" id="carousel-584841" data-interval="3000">
                <ol class="carousel-indicators">
                    <li class="active" data-slide-to="0" data-target="#carousel-584841">
                    </li>
                    <li data-slide-to="1" data-target="#carousel-584841">
                    </li>
                    <li data-slide-to="2" data-target="#carousel-584841">
                    </li>
                </ol>
                <div class="carousel-inner">
                    <div class="item active">
                        <img alt="Carousel Bootstrap First" src="<?=$this->options->themeUrl?>/images/home.carousel.one.jpg" />
                        <div class="carousel-caption">
                            <h4>
                                Make great films, leave the rest to us.
                            </h4>
                            <p>
                                As an artist, you can focus on the film creation - our partner networks will make sure they are discovered by the world.
                            </p>
                        </div>
                    </div>
                    <div class="item">
                        <img alt="Carousel Bootstrap Second" src="<?=$this->options->themeUrl?>/images/home.carousel.two.jpg" />
                        <div class="carousel-caption">
                            <h4>
                                Discover great independent content
                            </h4>
                            <p>
                                IndiePlat brings great content from independent creators to screens near you.
                            </p>
                        </div>
                    </div>
                    <div class="item">
                        <img alt="Carousel Bootstrap Third" src="<?=$this->options->themeUrl?>/images/home.carousel.three.jpg">
                        <div class="carousel-caption">
                            <h4>
                                Connect with great people and ideas.
                            </h4>
                            <p>
                                "If it can be written, or thought, it can be filmed." - Stanley Kubrick
                            </p>
                        </div>
                    </div>
                <!-- </div> <a class="left carousel-control" href="#carousel-584841" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#carousel-584841" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a> -->
            </div>
        </div>
    </div>
</div>
</div>
<!-- End Carousel -->

<!-- Add Spacing -->
<br><br><br><br>

<!-- Begin Featured Videos -->
<div class="featured-videos">
    <!-- <h1><?=Language::getText('featured_videos')?></h1> -->
    <h1>Curator's Picks</h1>
    <div class="video-list">
        <?php if (!empty ($featured_videos)): ?>
            <?php $this->repeatingBlock('video.phtml', array_slice($featured_videos, 0, 4)); ?>
        <?php else: ?>
            <div class="block"><strong><?=Language::getText('no_videos')?></strong></div>
        <?php endif; ?>
    </div>

</div>
<!-- End Featured Videos -->

<!-- Begin Recent Videos -->
<div class="recent-videos">
    <!-- <h1><?=Language::getText('recent_videos')?></h1> -->
    <h1>Latest Films</h1>
    <div class="video-list">
        <?php if (!empty ($recent_videos)): ?>
            <?php $this->repeatingBlock('video.phtml', array_slice($recent_videos, 0, 10)); ?>
        <?php else: ?>
            <div class="block"><strong><?=Language::getText('no_videos')?></strong></div>
        <?php endif; ?>
    </div>

</div>
<!-- End Recent Videos --> 
