<!-- BEGIN NAV -->
<nav class="navbar navbar-inverse" role="navigation"><!-- style="margin-top: 10px;" -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
                        </button> <a class="navbar-brand" href="<?=HOST?>/">IndiePlat</a>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="<?=HOST?>/videos/">Films</a>
                            </li>
                            <li>
                                <a id="modal-855933" href="<?=HOST?>/members/" role="button" class="btn" data-toggle="modal">Artists</a>
                            </li>
                                <?php if ($config->enableUserUploads): ?>
                                    <li class="<?=($this->options->page == 'account_upload') ? 'active' : ''?>"><a href="<?=HOST?>/account/upload/"><?=Language::GetText('upload')?></a></li>
                                    <?php endif; ?> 
                            <!-- <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong class="caret"></strong></a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="#">Action</a>
                                    </li>
                                    <li>
                                        <a href="#">Another action</a>
                                    </li>
                                    <li>
                                        <a href="#">Something else here</a>
                                    </li>
                                    <li class="divider">
                                    </li>
                                    <li>
                                        <a href="#">Separated link</a>
                                    </li>
                                    <li class="divider">
                                    </li>
                                    <li>
                                        <a href="#">One more separated link</a>
                                    </li>
                                </ul>
                            </li> -->
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a id="modal-855933" href="#modal-container-855933" role="button" class="btn" data-toggle="modal">Login</a>
                            </li>
                            <!-- <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong class="caret"></strong></a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="#">Action</a>
                                    </li>
                                    <li>
                                        <a href="#">Another action</a>
                                    </li>
                                    <li>
                                        <a href="#">Something else here</a>
                                    </li>
                                    <li class="divider">
                                    </li>
                                    <li>
                                        <a href="#">Separated link</a>
                                    </li>
                                </ul>
                            </li> -->
                            <!-- <form class="navbar-form navbar-left" role="search">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Search">
                                </div>
                                <button type="submit" class="btn btn-default">
                                    Search
                                </button>
                            </form> -->
                            <form class="navbar-form navbar-left" role="search">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Search" id="search-query-3">
                                        <span class="input-group-btn">
                                            <button type="submit" class="btn"><span class="fui-search"></span></button>
                                        </span>
                                    </div>
                                </div>
                            </form>
                        </ul>
                    </div>
                </nav>

<!-- BEGIN NAV -->

<!-- END HEADER -->
