<!DOCTYPE html>
<html>
<head>
<title><?=$meta->title?></title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="baseUrl" content="<?=HOST?>" />
<meta name="themeUrl" content="<?=$this->options->themeUrl?>" />
<?php $this->writeMeta(); ?>
<?php Plugin::triggerEvent('theme.head'); ?>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Loading Bootstrap -->
<link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/css/vendor/bootstrap.min.css" rel="stylesheet">
<!-- Loading Flat UI Pro -->
<link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/css/flat-ui-pro.css" rel="stylesheet">
<!-- <link rel="shortcut icon" type="image/x-icon" href="<?=$this->options->themeUrl?>/images/favicon.ico" />
<link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/css/main.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/css/pages.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/css/responsive.css" /> -->
<link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/css/videojs-sublime-skin.min.css" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<?php $this->writeCSS(); ?>

</head>
<body class="<?=$this->cssHooks()?>">
<?php Plugin::triggerEvent('theme.body'); ?>
    
<?php $this->block('header.phtml'); ?>

<div class="container">
    <div class="row">

        <!-- BEGIN MAIN CONTENT -->
        <main class="col-md-12">
            <?=$this->body()?>
        </main>
        <!-- END MAIN CONTENT -->

    </div>
</div>

<?php $this->block('footer.phtml'); ?>
    
<script type="text/javascript" src="<?=$this->options->themeUrl?>/js/jquery.min.js"></script>
<script type="text/javascript" src="<?=$this->options->themeUrl?>/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="<?=$this->options->themeUrl?>/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?=$this->options->themeUrl?>/js/general.js"></script>
<script type="text/javascript" src="<?=$this->options->themeUrl?>/js/annotator.min.js"></script>
<!-- Start Facebook SDK -->
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1116913425020741',
      xfbml      : true,
      version    : 'v2.5'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
<!-- End Facebook SDK -->
<?php $this->writeJs(); ?>

</body>
</html>
